services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Service\Permission\ElementPermissionServiceInterface:
        class: Pimcore\Bundle\GenericDataIndexBundle\Service\Permission\ElementPermissionService

    Pimcore\Bundle\GenericDataIndexBundle\Service\Permission\PermissionServiceInterface:
        class: Pimcore\Bundle\GenericDataIndexBundle\Service\Permission\PermissionService

    Pimcore\Bundle\GenericDataIndexBundle\Service\Permission\UserPermissionServiceInterface:
        class: Pimcore\Bundle\GenericDataIndexBundle\Service\Permission\UserPermissionService