services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Repository\IndexQueueRepository:
        arguments:
            - "@doctrine.orm.pimcore_generic_data_index_entity_manager"

