services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Service\Workflow\WorkflowServiceInterface:
        class: Pimcore\Bundle\GenericDataIndexBundle\Service\Workflow\WorkflowService