services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pimcore\Bundle\GenericDataIndexBundle\Service\Workspace\WorkspaceServiceInterface:
    class: Pimcore\Bundle\GenericDataIndexBundle\Service\Workspace\WorkspaceService

  Pimcore\Bundle\GenericDataIndexBundle\Service\Workspace\QueryServiceInterface:
    class: Pimcore\Bundle\GenericDataIndexBundle\Service\Workspace\QueryService