services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\LanguageService: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexUpdateService: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexQueueService: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexQueue\QueueMessagesDispatcher: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexQueue\EnqueueService: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\SearchIndexConfigService: ~

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexService\IndexService: ~

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexService\ElementTypeAdapter\ElementTypeAdapterService: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexService\ElementTypeAdapter\AssetTypeAdapter: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexService\ElementTypeAdapter\DataObjectTypeAdapter: ~

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexService\IndexHandler\AssetIndexHandler: ~
    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\IndexService\IndexHandler\DataObjectIndexHandler: ~

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionService:
        arguments:
            - '@pimcore.generic_data_index.object.search_index_field_definition_locator'

    pimcore.generic_data_index.object.search_index_field_definition_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: [ 'container.service_locator' ]
        arguments:
            - [ ]