services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\Asset\AssetSearchServiceInterface:
      class: Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\Asset\AssetSearchService


  Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\SearchHelperInterface:
      class: Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\SearchHelper


  Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\SearchProviderInterface:
      class: Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\SearchProvider