parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # INSTALLER
    #
    Pimcore\Bundle\GenericDataIndexBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreGenericDataIndexBundle')"