services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  'generic-data-index.test.service.asset-search-service': '@Pimcore\Bundle\GenericDataIndexBundle\Service\Search\SearchService\Asset\AssetSearchServiceInterface'