services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\TextKeywordAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "wysiwyg" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "textarea" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "select" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "multiselect" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "input" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "calculatedValue" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "country" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "countrymultiselect" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "language" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "languagemultiselect" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "table" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "password" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "time" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "user" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\NumericAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "numeric" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "slider" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\DateAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "date" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "datetime" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "dateRange" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\LocalizedFieldsAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "localizedfields" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\QuantityValueAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "quantityValue" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "inputQuantityValue" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\BooleanAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "checkbox" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "booleanSelect" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\RelationAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "manyToOneRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "manyToManyObjectRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "manyToManyRelation" }


    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\AdvancedManyToManyRelationAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "advancedManyToManyRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "advancedManyToManyObjectRelation" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\ObjectBrickAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "objectbricks" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\FieldCollectionAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "fieldcollections" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\ClassificationStoreAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "classificationstore" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\RgbaColorAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "rgbaColor" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\QuantityValueRangeAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "quantityValueRange" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\NumericRangeAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "numericRange" }


    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\GeographicPointAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "geopoint" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "geopolygon" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "geopolyline" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\GeographicBoundsAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "geobounds" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\UrlSlugAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "urlSlug" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\LinkAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "link" }

    Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\DataObject\FieldDefinitionAdapter\BlockAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "block" }