services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\TextKeywordAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "wysiwyg" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "textarea" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "select" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "multiselect" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "input" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "calculatedValue" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "country" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "countrymultiselect" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "language" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "languagemultiselect" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "table" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\NumericAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "numeric" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "slider" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\DateAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "date" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "datetime" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\LocalizedFieldsAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "localizedfields" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\QuantityValueAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "quantityValue" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "inputQuantityValue" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\BooleanAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "checkbox" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\RelationAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "manyToOneRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "manyToManyObjectRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "manyToManyRelation" }


    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\AdvancedManyToManyRelationAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "advancedManyToManyRelation" }
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "advancedManyToManyObjectRelation" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\ObjectBrickAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "objectbricks" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\FieldCollectionAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "fieldcollections" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\ClassificationStoreAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "classificationstore" }

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\DataObject\FieldDefinitionAdapter\RgbaColorAdapter:
        shared: false
        tags:
            - { name: "pimcore.generic_data_index.data-object.search_index_field_definition", type: "rgbaColor" }