services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\GenericDataIndexBundle\Service\SearchIndex\Asset\MetadataMappingProvider\PredefinedAssetMetadataProvider:
        tags:
            - { name: "pimcore.generic_data_index.asset.mapping_provider", type: "predefined" }