imports:
  - { resource: messenger.yaml }

pimcore_generic_data_index:
  index_service:
    search_settings:
      list_page_size: 60
      list_max_filter_options: 500
      search_analyzer_attributes:
        text:
          fields:
            analyzed_ngram:
              type: text
              analyzer: generic_data_index_ngram_analyzer
              search_analyzer: generic_data_index_whitespace_analyzer
            analyzed:
              type: text
              analyzer: standard
              search_analyzer: generic_data_index_whitespace_analyzer

    index_settings:
      index:
        mapping:
          nested_fields:
            limit: 200
          total_fields:
            limit: 100000
      number_of_shards: 1
      number_of_replicas: 0
      max_ngram_diff: 30
      max_result_window: 10000
      analysis:
        analyzer:
          generic_data_index_ngram_analyzer:
            tokenizer: generic_data_index_ngram_tokenzier
            filter:
              - lowercase
          generic_data_index_whitespace_analyzer:
            tokenizer: generic_data_index_whitespace_tokenzier
            filter:
              - lowercase
          generic_data_index_path_analyzer:
            tokenizer: generic_data_index_path_tokenizer
        normalizer:
          generic_data_index_sort_normalizer:
            type: custom
            filter:
              - lowercase
          generic_data_index_sort_truncate_normalizer:
            type: custom
            char_filter:
              - generic_data_index_sort_truncate
            filter:
              - lowercase
        tokenizer:
          generic_data_index_ngram_tokenzier:
            type: ngram
            min_gram: 3
            max_gram: 25
            token_chars: [ letter, digit ]
          generic_data_index_whitespace_tokenzier:
            type: whitespace
          generic_data_index_path_tokenizer:
            type: "path_hierarchy"
        char_filter:
          generic_data_index_sort_truncate:
            type: pattern_replace
            pattern: ^(.{256})(.*)$
            replacement: $1
    system_fields_settings:
      general:
        id:
          type: long
        elementType:
          type: keyword
        parentId:
          type: long
        creationDate:
          type: date
        modificationDate:
          type: date
        type:
          type: keyword
        key:
          type: keyword
          fields:
            analyzed_ngram:
              type: text
              analyzer: generic_data_index_ngram_analyzer
              search_analyzer: generic_data_index_whitespace_analyzer
            analyzed:
              type: text
              analyzer: standard
              search_analyzer: generic_data_index_whitespace_analyzer
            sort:
              type: keyword
              normalizer: generic_data_index_sort_normalizer
        path:
          type: text
          analyzer: generic_data_index_path_analyzer
          fields:
            keyword:
              type: keyword
            sort:
              type: keyword
              normalizer: generic_data_index_sort_normalizer
        fullPath:
          type: text
          analyzer: generic_data_index_path_analyzer
          fields:
            keyword:
              type: keyword
            sort:
              type: keyword
              normalizer: generic_data_index_sort_normalizer
        pathLevels:
          type: nested
          properties:
            level:
              type: integer
            name:
              type: keyword
        pathLevel:
          type: integer
        tags:
          type: integer
        parentTags:
          type: integer
        thumbnail:
          type: keyword
        userOwner:
          type: integer
        userModification:
          type: integer
        lock:
          type: keyword
        isLocked:
          type: boolean
        hasWorkflowWithPermissions:
          type: boolean
        dependencies:
          type: object
          properties:
            asset:
              type: long
            document:
              type: long
            object:
              type: long
      document:
        published:
          type: boolean
        controller:
          type: keyword
        template:
          type: keyword
        contentMainDocumentId:
          type: integer
        supportsContentMain:
          type: boolean
        missingRequiredEditable:
          type: boolean
        staticGeneratorEnabled:
          type: boolean
        staticGeneratorLifetime:
          type: integer
        title:
          type: keyword
        description:
          type: keyword
        prettyUrl:
          type: keyword
        sourceId:
          type: integer
        propertiesFromSource:
          type: boolean
        childrenFromSource:
          type: boolean
        subject:
          type: keyword
        from:
          type: keyword
        replyTo:
          type: keyword
        to:
          type: keyword
        cc:
          type: keyword
        bcc:
          type: keyword
        internal:
          type: integer
        internalType:
          type: keyword
        direct:
          type: keyword
        linktype:
          type: keyword
        href:
          type: keyword
      data_object:
        published:
          type: boolean
        classname:
          type: keyword
          fields:
            sort:
              type: keyword
              normalizer: generic_data_index_sort_normalizer
        classDefinitionIcon:
          type: keyword
        index:
          type: integer
      asset:
        mimetype:
          type: keyword
        fileSize:
          type: long
        thumbnail:
          type: keyword
        imageThumbnail:
          type: keyword
        width:
          type: integer
        height:
          type: integer
        duration:
          type: float
        text:
          type: keyword
          ignore_above: 256
          fields:
            analyzed_ngram:
              type: text
              analyzer: generic_data_index_ngram_analyzer
              search_analyzer: generic_data_index_whitespace_analyzer
            analyzed:
              type: text
              analyzer: standard
              search_analyzer: generic_data_index_whitespace_analyzer