framework:
    messenger:
        enabled: true
        transports:
            pimcore_generic_data_index_queue: 'doctrine://default?queue_name=pimcore_index_queues'
            pimcore_generic_data_index_sync: 'sync://'
        routing:
            Pimcore\Bundle\GenericDataIndexBundle\Message\IndexUpdateQueueMessage: pimcore_generic_data_index_queue
            Pimcore\Bundle\GenericDataIndexBundle\Message\DispatchQueueMessagesMessage: pimcore_generic_data_index_queue
        buses:
            messenger.bus.pimcore-generic-data-index:
                middleware:
                    - 'Pimcore\Bundle\GenericDataIndexBundle\Service\Messenger\Middleware\CollectGarbageMiddleware'
