services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pimcore\Bundle\GenericDataIndexBundle\SearchIndexAdapter\OpenSearch\Search\Modifier\Filter\Tree\ParentIdFilterModifier: ~