name: Qodana
on:
  schedule:
    - cron: '0 01 * * *' # Run once per day
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - '**.yml'
      - '**.yaml'
    branches:
      - '*'
      - '**'
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - '**.php'
      - '**.yml'
      - '**.yaml'
    branches:
      - '*'
      - '**'

jobs:
  qodana-check-workflow:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-qodana-check.yaml@main
    secrets:
      COMPOSER_PIMCORE_REPO_PACKAGIST_TOKEN: ${{ secrets.COMPOSER_PIMCORE_REPO_PACKAGIST_TOKEN }}
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
